# Live Coding 1 🎥

## Deep Learning Basics with PyTorch

What we're going to cover:

- [torch.Tensor](https://pytorch.org/docs/stable/tensors.html): High-dimensional arrays, similar to NumPy arrays.
 
- [nn Modules](https://pytorch.org/docs/stable/nn.html):
  - [nn.Module](https://pytorch.org/docs/stable/generated/torch.nn.Module.html): Base class for all neural network modules.
  - [nn.Linear](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html): Applies a linear transformation to the incoming data.
  - [nn.Conv2d](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html): Applies a 2D convolution over an input signal.

- [Activation Functions](https://pytorch.org/docs/stable/nn.html#non-linear-activations):
  - [nn.ReLU](https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html): Rectified Linear Unit.
  - [nn.Sigmoid](https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html): Sigmoid function.
  - [nn.Tanh](https://pytorch.org/docs/stable/generated/torch.nn.Tanh.html): Hyperbolic tangent function.

- [Optim](https://pytorch.org/docs/stable/optim.html): Optimization algorithms.
  - [torch.optim.SGD](https://pytorch.org/docs/stable/optim.html#torch.optim.SGD): Stochastic Gradient Descent.
  - [torch.optim.Adam](https://pytorch.org/docs/stable/optim.html#torch.optim.Adam): Adam algorithm.

- [Loss Functions](https://pytorch.org/docs/stable/nn.html#loss-functions):
  - [nn.CrossEntropyLoss](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html): Combines `nn.LogSoftmax` and `nn.NLLLoss`.

  - [nn.MSELoss](https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html): Mean squared error loss.
  - [nn.BCELoss](https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html): Binary cross entropy loss.

- [Data Loading and Processing](https://pytorch.org/docs/stable/data.html):
  - [torch.utils.data.DataLoader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader): Data loader.
  - [torchvision.datasets](https://pytorch.org/vision/stable/datasets.html): Standard datasets.
  - [torchvision.transforms](https://pytorch.org/vision/stable/transforms.html): Common image transformations.

- [Training Loop](https://pytorch.org/tutorials/beginner/basics/optimization_tutorial.html): Putting it all together to train a model.
- [Saving and Loading Models](https://pytorch.org/tutorials/beginner/saving_loading_models.html): Persisting and restoring models.

In [65]:
import torch

## Tensor

In [66]:
s = torch.tensor(1)
s

tensor(1)

In [67]:
s.ndim

0

In [68]:
s.shape

torch.Size([])

In [69]:
vec = torch.Tensor([1, 2, 4])
vec

tensor([1., 2., 4.])

In [70]:
vec.ndim

1

In [71]:
vec.shape

torch.Size([3])

In [72]:
matrix = torch.Tensor([[1, 2, 3],
                       [3, 4, 4]])
matrix

tensor([[1., 2., 3.],
        [3., 4., 4.]])

In [73]:
matrix.shape

torch.Size([2, 3])

In [74]:
matrix.ndim

2

In [75]:
tensor = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(2, 3, 2)
tensor

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [76]:
tensor.ndim

3

In [77]:
tensor.shape

torch.Size([2, 3, 2])

In [78]:
tensor[1][1][1]

tensor(10.)

## Tensor Operations 

In [79]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([3, -2, 5])

In [80]:
a + b 

tensor([4., 0., 8.])

In [81]:
a - b 

tensor([-2.,  4., -2.])

In [82]:
a * b # element wise

tensor([ 3., -4., 15.])

In [83]:
a / b

tensor([ 0.3333, -1.0000,  0.6000])

In [84]:
torch.dot(a, b)

tensor(14.)

In [85]:
m1 = torch.Tensor([[1, 2, 3],
                   [3, 4, 4]])

m2 = torch.Tensor([[1, 2, 3],
                  [3, 4, 4]])

In [86]:
m1

tensor([[1., 2., 3.],
        [3., 4., 4.]])

In [87]:
m1.t()

tensor([[1., 3.],
        [2., 4.],
        [3., 4.]])

In [88]:
m1.shape

torch.Size([2, 3])

In [89]:
m1.t().shape

torch.Size([3, 2])

In [90]:
torch.mm(m1, m2.t())

tensor([[14., 23.],
        [23., 41.]])

In [91]:
m1 @ m2.t()

tensor([[14., 23.],
        [23., 41.]])

In [92]:
torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(2, 3, 2)
tensor

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [93]:
tensor.shape

torch.Size([2, 3, 2])

In [94]:
m1.shape

torch.Size([2, 3])

In [95]:
res = tensor @ m1
res

tensor([[[ 7., 10., 11.],
         [15., 22., 25.],
         [23., 34., 39.]],

        [[31., 46., 53.],
         [39., 58., 67.],
         [47., 70., 81.]]])

In [96]:
res.shape

torch.Size([2, 3, 3])

## Other Operations

In [99]:
tensor = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [100]:
tensor.shape

torch.Size([12])

In [102]:
tensor.reshape(3, 4) # 3 x 4 = 12 

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [104]:
tensor.reshape(3, 2, 2)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])